name = "NonConvexPenalizedRegression"
uuid = "393d5197-c0a3-4293-bd2f-5829bf091ab1"
authors = ["Pierre Navaro"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Aqua = "0.8"
DocStringExtensions = "0.9"
LinearAlgebra = "1"
RData = "0.8, 1"
Random = "1"
Statistics = "1"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "RData"]
